add_newline = false

format = """$directory$git_branch$git_commit$git_state$git_metrics$git_status: """
palette = "nord"

right_format = """$all"""

command_timeout = 1000

[character]
vimcmd_symbol = ''
success_symbol = ''
error_symbol = ''

[directory]
style = "nord8"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
format = '[\($hash$tag\)]($style)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'

[git_metrics]
format = '([+$added]($added_style) )([-$deleted]($deleted_style))'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[palettes.nord]
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"
red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
